project:
  type: website
  output-dir: docs

website:
  title: "quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - explorer.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  after:
    - ./copy-html.sh
