---
title: "Data Explorer API and Shiny App"
---

## API in R

Die API wurde mit dem R-Paket [plumber](https://www.rplumber.io/) erstellt. Plumber ermöglicht es, R-Funktionen als HTTP-Endpunkte bereitzustellen. Das Paket wandelt R-Funktionen automatisch in eine REST API um, indem spezielle Kommentare verwendet werden, die den Endpunkt und die HTTP-Methode definieren. Die API kann dann lokal oder auf einem Server gehostet werden.

Live: [Swagger UI Demo](https://connect.cynkra.com/sgods-api/)

Code: [GitHub](https://github.com/cynkra/sgods/blob/main/api/plumber.R)


## Data Explorer

Es gibt verschiedene Möglichkeiten, um einen Data Explorer zu erstellen. Wir untersuchen drei verschiedene Ansätze:


### Standard Webtechnologien (z.B. Vue.js)

Das ist eine non-R-Lösung, die auf einem beliebigen Webserver gehostet werden kann. Trotzdem ist sie relativ einfach zu implementieren:

Live: [Vue.js Demo](https://cynkra.github.io/sgods/vue/)

Code: [GitHub](https://github.com/cynkra/sgods/blob/main/docs/vue/index.html)


#### Vorteile

- Standard Webtechnologien
- Sehr viele Freiheiten in der Gestaltung

#### Nachteile

- JavaScript- und HTML-Kenntnisse werden benötigt, R ist nicht ausreichend



### R Shiny

Shiny ist ein offensichtlicher Kandidat.

Live: [Shiny App Demo](https://connect.cynkra.com/sgods-app/)

Code: [GitHub](https://github.com/cynkra/sgods/blob/main/shiny/app.R)

#### Vorteile

- Kann in R geschrieben werden

#### Nachteile

- Benötigt Connect und Shiny Server
- Beträchtlicher Overhead


### R + Quarto

Live: [Demo](https://cynkra.github.io/sgods/explorer.html)

Code: [GitHub](https://github.com/cynkra/sgods/blob/main/explorer.qmd)


#### Vorteile

- Kann in R geschrieben werden
- Gestaltungsmöglichkeiten von Quarto

#### Nachteile

- Gestaltungsmöglichkeiten von Quarto




### Weitere Ideen

- Daten auf https://opendata.swiss veröffentlichen?